steps:
  # Dockerイメージをビルドするステップ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/coc-character-sheet:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/coc-character-sheet:latest'
      - '.'

# ビルドしたイメージをContainer Registryにプッシュする
images:
  - 'gcr.io/$PROJECT_ID/coc-character-sheet:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/coc-character-sheet:latest'

options:
  logging: CLOUD_LOGGING_ONLY